name: Deploy to GCR with github actions

on:
  push:
    branches:
      - main

jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v3
      - name: Building and pushing the image
        uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          gcloud_service_key:  ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: gcr.io
          project_id: teak-alloy-391202
          image_name: simple-docker
          image_tag: latest
          dockerfile: ./Dockerfile
          context: ./
          build_args: PORT=3456

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: 'cloud-run'
          image: 'gcr.io/teak-alloy-391202/simple-docker:latest'

      - name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
